[server]
host = "0.0.0.0"
port = "8080"
readTimeout = "5s"
writeTimeout = "10s"
idleTimeout = "120s"

[logging]
level = "info"
format = "text"

[cors]
allowedOrigins = ["*"]
allowedMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowedHeaders = ["*"]
maxAge = 86400

[gateway]

  [[gateway.routes]]
  path = "/login"
  method = "POST"
  upstreamURL = "http://auth-service:8081"
  rewritePath = "/"

  [[gateway.routes]]
  path = "/request"
  method = "POST"
  upstreamURL = "http://saga-orchestrator:8082"
  rewritePath = "/v1/sagas/reviews/start"

  [[gateway.routes]]
  path = "/rag/query"
  method = "POST"
  upstreamURL = "http://review-rag:8083"
  rewritePath = "/"

